name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: dependency (ubuntu)
      run: |
        apt -qy install \
        make python3 python3-pip

    - id: step1
      name: make
      run: make
    
    - id: step2
      name: test pybind11
      run: make pybind

    - id: step3
      name: make test
      run: make test
