name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: dependency (ubuntu)
      run: |
        sudo apt-get -qy install \
        make python3 python3-pip

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pybind11

    - id: step1
      name: make
      run: make
    
    - id: step2
      name: test pybind11
      run: make pybind
    
    - id: step3
      name: make test
      run: make test

    - id: step4
      name: make test
      run: make testcpp
