name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: |
        echo "cd src/"
        cd src/
        make
    - name: make test
      run: make test
    - name: make clean
      run: make clean
