name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - uses: actions/checkout@v2
    - id: step1
      name: make test
      run: make test
    - id: step2
      name: test pybind11
      run: make pybind
